[package]
name = "dnsco"
version = "0.1.0"
authors = ["Dennis Collective <dennis.collective@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_json = "1"
actix-web= "^1.0.0-beta.2"

oauth2 = "1"
url = "1"
reqwest = "0"
failure = "0.1.5"
