[package]
name = "dnsco"
version = "0.1.0"
authors = ["Dennis Collective <dennis.collective@gmail.com>"]
edition = "2018"

[dependencies]
actix-web= "^1.0.0-beta.2"
askama = "0.8.0"
env_logger= "0.6.1"
failure = "0.1.5"
http = "0.1.17"
serde = "1"
serde_json = "1"
strava = { path="./strava"}
url = "1"

[workspace]
members = [ ".", "strava"]