[package]
name = "strava"
version = "0.1.0"
authors = ["Dennis Collective <dennis.collective@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
failure = "0.1.5"
oauth2 = "^2.0.0-beta.2"

reqwest = "0"
serde = "1"
serde_json = "1"
url = "1"

